# Generated by Django 3.1 on 2020-09-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what_food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='food',
            name='url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
