# Generated by Django 3.1 on 2020-09-13 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('what_food', '0002_auto_20200911_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='url',
        ),
    ]
